version: '3.9'

services:
  mongo_server:
    container_name: mongo
    image: mongo:${MONGO_TAG}
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mqtt
    volumes:
      - ../../apps/emqx/etc/certs/cert.pem:/etc/certs/cert.pem
      - ../../apps/emqx/etc/certs/key.pem:/etc/certs/key.pem
    networks:
      - emqx_bridge
    ports:
      - "27017:27017"
    command:
      - /bin/bash
      - -c
      - |
        cat /etc/certs/key.pem /etc/certs/cert.pem >  /etc/certs/mongodb.pem
        mongod --ipv6 --bind_ip_all --sslMode requireSSL --sslPEMKeyFile /etc/certs/mongodb.pem

