version: '3.9'

services:
  redis_server:
    container_name: redis
    image: redis:${REDIS_TAG}
    volumes:
      - ../../apps/emqx/etc/certs/cacert.pem:/etc/certs/ca.crt
      - ../../apps/emqx/etc/certs/cert.pem:/etc/certs/redis.crt
      - ../../apps/emqx/etc/certs/key.pem:/etc/certs/redis.key
    command:
      - redis-server
      - "--bind 0.0.0.0 ::"
      - --requirepass public
      - --tls-port 6380
      - --tls-cert-file /etc/certs/redis.crt
      - --tls-key-file /etc/certs/redis.key
      - --tls-ca-cert-file /etc/certs/ca.crt
    restart: always
    networks:
      - emqx_bridge
